added build static node lib

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -87,3 +87,60 @@ jobs:
 #            "${OUTFILE}" --grants=read=uri=http://acs.amazonaws.com/groups/global/AllUsers
 #        env:
 #          OUTFILE: s3://distribution.concordium.software/tools/linux/database-exporter_${{ steps.set_version.outputs.TAG }}.deb
+
+  build-p2p-bootstrapper:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Precheck - Validate Version and Check S3 for existing files
+        run: |
+          # Check if the file already exists in S3
+          OUTFILE="s3://distribution.concordium.software/tools/linux/p2p-bootstrapper_${{ env.VERSION }}.deb"
+          totalFoundObjects=$(aws s3 ls "$OUTFILE" --summarize | grep "Total Objects: " | sed "s/[^0-9]*//g")
+          if [ "$totalFoundObjects" -ne "0" ]; then
+            echo "error: $OUTFILE already exists"
+            exit 1
+          fi
+
+      - name: Build Static Node Binaries
+        run: ./scripts/static-binaries/build-static-binaries.sh
+        env:
+          STATIC_LIBRARIES_IMAGE_TAG: ${{ env.STATIC_LIBRARIES_IMAGE_TAG }}
+
+      - name: Build Docker Image
+        uses: docker/build-push-action@v6
+        with:
+          context: .
+          push: false
+          file: scripts/bootstrapper/Dockerfile
+          tags: build-deb:${{ github.run_id }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+          build-args: |
+            ubuntu_version=${{ env.UBUNTU_VERSION }}
+            version=${{ env.VERSION }}
+            static_binaries_image_tag=${{ env.STATIC_LIBRARIES_IMAGE_TAG }}
+          labels: |
+            ubuntu_version=${{ env.UBUNTU_VERSION }}
+            version=${{ env.VERSION }}
+            static_binaries_image_tag=${{ env.STATIC_LIBRARIES_IMAGE_TAG }}
+
+#      - name: Run Docker Container to Generate Output
+#        run: |
+#          docker run \
+#            --env EXTERNAL_UID=${{ env.EXTERNAL_UID }} \
+#            --env EXTERNAL_GID=${{ env.EXTERNAL_GID }} \
+#            -v "${{ env.OUT_DIR }}":/out \
+#            build-deb:${{ github.run_id }}
+#
+#      - name: Push Debian Package to S3
+#        run: |
+#          aws s3 cp "${{ env.OUT_DIR }}/p2p-bootstrapper_${{ steps.set_version.outputs.TAG }}.deb" \
+#            "${OUTFILE}" --grants=read=uri=http://acs.amazonaws.com/groups/global/AllUsers
+#        env:
+#          OUTFILE: s3://distribution.concordium.software/tools/linux/p2p-bootstrapper_${{ steps.set_version.outputs.TAG }}.deb
