build windows version

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -149,3 +149,38 @@ jobs:
 #            "${OUTFILE}" --grants=read=uri=http://acs.amazonaws.com/groups/global/AllUsers
 #        env:
 #          OUTFILE: s3://distribution.concordium.software/tools/linux/p2p-bootstrapper_${{ steps.set_version.outputs.TAG }}.deb
+
+  build-windows-node:
+    runs-on: windows-latest
+
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+        with:
+          submodules: recursive
+
+      - name: Precheck - Validate Version and Check S3 for existing files
+        run: |
+          # Check if the file already exists in S3
+          OUTFILE="s3://distribution.concordium.software/tools/linux/p2p-bootstrapper_${{ env.VERSION }}.deb"
+          totalFoundObjects=$(aws s3 ls "$OUTFILE" --summarize | grep "Total Objects: " | sed "s/[^0-9]*//g")
+          if [ "$totalFoundObjects" -ne "0" ]; then
+            echo "error: $OUTFILE already exists"
+            exit 1
+          fi
+
+      - name: Set Workspace Path (Custom for Windows to avoid long paths)
+        run: mkdir C:\\node-ws
+
+      - name: Build Windows Node
+        run: |
+          powershell -File ./scripts/distribution/windows/build-all.ps1 -nodeVersion ${{ env.VERSION }}
+
+#      - name: Upload Windows MSI to S3
+#        run: |
+#          BASE_OUTFILE='s3://distribution.concordium.software/windows/'
+#          OUTFILE="${BASE_OUTFILE}Node-${{ steps.set_version.outputs.TAG }}.msi"
+#          aws s3 cp ./service/windows/installer/Node.msi $OUTFILE --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
+#        env:
+#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
